### ISSUE TITLE
SSH requires manual confirmation on first connect.

### ISSUE THREAD

**Issue by etherneet** [lep/teadb#1]
https://github.com/lep/teadb/blob/eb05c4495475181285cf137ae901729d03649f13/tea#L441

Also an option for configuring sync might be useful 😸

**Comment by lep** [comment]
This script is mostly writen for me by me and i use ssh authorized_keys 
for passwordless login (i guess that is what you mean?). As you've to 
distribute the tea executable prior anyways there shouldn't be any login 
woes.
